//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 11 2015 18:36:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>
#import "apple80211_ioctl.h"
#import "apple80211_var.h"
#import "apple80211_wps.h"
#import "Apple80211Err.h"
#import <CoreWLAN/CoreWLAN.h>

__BEGIN_DECLS

struct Apple80211;
typedef struct Apple80211 *Apple80211Ref;

CWErr Apple80211Open(Apple80211Ref *handle); //Open Conection
CWErr Apple80211Close(Apple80211Ref handle);
CWErr Apple80211BindToInterface(Apple80211Ref handle, CFStringRef interface);
CWErr Apple80211Scan(Apple80211Ref handle, CFArrayRef *scanResult, CFDictionaryRef parametrs);

CWErr Apple80211SetPower(Apple80211Ref handle, uint32_t power);
CWErr Apple80211GetPower(Apple80211Ref wref, uint32_t *power);
//int Apple80211Set(Apple80211Ref handle, CFStringRef str, uint32_t val);
CWErr ACInterfaceCopyInfo(Apple80211Ref handle);
CWErr ACNetworkCreate(CFStringRef ssid);

CWErr Apple80211Disassociate(Apple80211Ref wref);
CWErr Apple80211Associate(Apple80211Ref handle, CFDictionaryRef SSID, CFStringRef pass);
//int Apple80211Associate2();

CWErr Apple80211Get(Apple80211Ref ref, CFStringRef chr, uint32_t val, CFTypeRef var, uint32_t var2);
CWErr Apple80211Set(Apple80211Ref ref, uint32_t type, uint32_t unkn, CFTypeRef var);

char *Apple80211ErrToStr(CWErr errCode);
CWErr Apple80211GetIfListCopy(Apple80211Ref handle, CFArrayRef *If_name_array);
CWErr Apple80211GetInfoCopy(Apple80211Ref wref, CFDictionaryRef *dict);
CWErr Apple80211CopyValue();

using Apple80211EventCallback = void(*)(CWErr err, Apple80211Ref wref,
                                        uint32_t event, void * eventData,
                                        uint32_t eventDataLen, void *context);
CWErr Apple80211EventMonitoringInit(Apple80211Ref wref,
                                    Apple80211EventCallback cb,
                                    void *userData, CFRunLoopRef runloop);
CWErr Apple80211StartMonitoringEvent(Apple80211Ref wref, uint32_t event);
CWErr Apple80211StopMonitoringEvent(Apple80211Ref wref, uint32_t event);
CWErr Apple80211EventMonitoringHalt(Apple80211Ref wref);

__END_DECLS

@interface AirPort : NSObject
{
    struct _AirPort *_ref;
}

+ (id)interfaceNames:(id *)arg1;
- (id)initWithInterfaceName:(id)arg1;
- (void)dealloc;
- (id)interfaceName;
- (void)setPower:(BOOL)arg1 error:(id *)arg2;
- (void)getPower:(id *)arg1 error:(id *)arg2;
- (BOOL)powerWithError:(id *)arg1;
- (void)setChannel:(id)arg1 error:(id *)arg2;
- (id)channelWithError:(id *)arg1;
- (id)staticConnectionParameters:(id *)arg1;
- (id)dynamicConnectionParameters:(id *)arg1;
- (id)regulatoryInfo:(id *)arg1;
- (id)capabilities:(id *)arg1;
- (id)preference:(id)arg1 error:(id *)arg2;
- (void)setPreference:(id)arg1 toValue:(id)arg2 error:(id *)arg3;
- (void)commitPreferencesWithError:(id *)arg1;
- (id)scanWithArgs:(id)arg1 error:(id *)arg2;
- (BOOL)associateToNetwork:(id)arg1 withArgs:(id)arg2 error:(id *)arg3;
- (BOOL)disassociateWithError:(id *)arg1;
- (BOOL)createIBSS:(id)arg1 error:(id *)arg2;
- (void)startMonitoringEvents:(id)arg1 onRunloop:(id)arg2 error:(id *)arg3;
- (void)stopMonitoringEventsWithError:(id *)arg1;

@end

